POST http://localhost:4000/api/v1/auth/register HTTP/1.1
HOST: my-server
Content-Type:application/json
Accept:application/json

{
    "name": "eric",
    "password": "secret",
    "email": "eric1@gmail.com"
}